---
- hosts: all
  tasks:
  - name: Stop Tomcat
    shell: docker-compose stop tomcat
    register: compose_stop
  - debug: var=compose_stop.stdout_lines
  - name: Start Tomcat
    shell: docker-compose -f docker-compose.yml up -d
    register: compose_start
  - debug: var=compose_start.stdout_lines
